version: '3.8'

services:
  # Servicio del backend (servidor)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m8-ep2-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server:/app
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "5000:5000"
    depends_on:
      - db # Si tienes una base de datos

  # Servicio del frontend (React)
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: m8-ep2-frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"  # El puerto que usas para React
    depends_on:
      - backend

  # Servicio para la base de datos (ejemplo: MongoDB)
  db:
    image: mongo
    container_name: m8-ep2-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:  # Volumen persistente para la base de datos
